/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function add(left: number, right: number): number

export declare function divide(left: number, right: number): number

export declare function multiply(left: number, right: number): number

export declare function subtract(left: number, right: number): number
